[book]
title = "SICP in Rust"
authors = ["x5zone"]
language = "zh-CN"
src = "."

[build]
build-dir = "book"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
additional-css = ["mdbook/custom.css"]
additional-js = ["mdbook/mathjax.js", "mdbook/comment.js"]
git-repository-url = "https://github.com/x5zone/rust-sicp-exercises"
edit-url-template = "https://github.com/x5zone/rust-sicp-exercises/edit/main/{path}"


